server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://localhost:3307/giftmanagement?characterEncoding=UTF-8&serverTimezone=UTC


    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: none #create update none

      show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    hidden-method:
      filter:
        enabled: true