server:
port: 8082


spring:
datasource:
driver-class-name: org.mariadb.jdbc.Driver
url: jdbc:mariadb://localhost:3307/giftManagement
username: root
password: system
jpa:
hibernate:
ddl-auto: none #create update none

show-sql: true
